name: YouTube Automation Bot

on:
  schedule:
    # JST 06:00 => UTC 21:00 (前日)
    - cron: '0 21 * * *'
    # JST 14:00 => UTC 05:00
    - cron: '0 5 * * *'
    # JST 20:00 => UTC 11:00
    - cron: '0 11 * * *'
  workflow_dispatch: # 手動実行用ボタン

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies (FFmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-noto-cjk imagemagick

      - name: Install libraries
        run: |
          pip install -r requirements.txt

      - name: Run Automation Script
        env:
          #OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          #YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          #YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          #YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: |
          # 時間に基づいて実行モードを決定するロジックはmain.py内に記述
          python src/main.py
